name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/telegram/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB }}

      - name: Build and push telegram image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/telegram/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/ava-telegram:${{ github.run_id }}

      - name: Update Terraform Configuration
        run: |
          sed -i "s|${{ secrets.DOCKERHUB_USER }}/ava-telegram:.*|${{ secrets.DOCKERHUB_USER }}/ava-telegram:${{ github.run_id }}|" main.tf
        working-directory: ./iac/environments/dev

      - name: Commit Terraform Changes
        run: |
          git config --global user.name 'Telegram Docker Build'
          git config --global user.email 'td.build@tailoredshapes.com'
          git add ./iac/environments/dev/main.tf
          git commit -m "Update Docker image tag in Terraform to ${{ github.run_id }}"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main



